### PR TITLE
Create Dice Rolling Simulator Using Python

### PR DESCRIPTION
**Pull request by Soumyajit2005**

### CODE REVIEW

**Comment by Soumyajit2005** [comment]
It is a dice rolling simulator using python. It is made using tkinter .random module etc.

**Comment by Soumyajit2005** [comment]
Why did you remove the hactoberfest label ?

**Comment by Rishi098** [comment]
Something missing in this code can't be merged

**Comment by Soumyajit2005** [comment]
Can you tell in details ?

**Comment by Soumyajit2005** [comment]
Guide me through what is wrong and I'll fix the issue and then please add the hactoberfest-accepted label

**Pull request merged**
